### ISSUE TITLE
Wifi List not coming up 

### ISSUE THREAD

**Issue by devarsh9** [omert08/esp_softap_provisioning#1]
Hi,

This is a very useful library and it is very handy too. 
I ran into an issue, I have used the author's example code .
After I connect my ESP32 device with WIFI and click ready in the applications following exception is thrown and WIFI list doesn't appear. Could you please help me out with this 

I/flutter ( 9053): │ #0   WiFiBlocSoftAP._mapLoadToState (package:esp_softap_provisioning_example/wifi_screen/wifi_bloc.dart:54:11)
I/flutter ( 9053): │ #1   <asynchronous suspension>
I/flutter ( 9053): 

I/flutter ( 9053): │ ⛔ Error scan WiFi network NoSuchMethodError: The method 'startScanWiFi' was called on null.
I/flutter ( 9053): │ ⛔ Receiver: null[0m
I/flutter ( 9053): │ ⛔ Tried calling: startScanWiFi()
I/flutter ( 9053): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Thanks in advance

**Comment by omert08** [comment]
Hello, thanks for the nice comments. 

prov object returns null from the following line, so you get this issue.

`prov = await softApService.startProvisioning(..)`

Please make sure you provided permissions for HTTP in AndroidManifest.xml for Android and Info.plist for iOS. Check README regarding how to update these files for HTTP permission. 

Hope it helps

**Comment by devarsh9** [comment]
I checked my AndroidManifest.xml it is according to the README file of the repository but the error still remains

**Comment by devarsh9** [comment]
I am using the same code as yours so I have similar AndroidManifest.xml as example code 


&lt;manifest xmlns:android="http://schemas.android.com/apk/res/android"    package="com.omert.esp_softap_provisioning_example"&gt;    &lt;uses-permission android:name="android.permission.INTERNET"/&gt;   &lt;application        android:label="esp_softap_provisioning_example"       android:usesCleartextTraffic="true"       android:icon="@mipmap/ic_launcher"&gt;        &lt;activity            android:name=".MainActivity"            android:launchMode="singleTop"            android:theme="@style/LaunchTheme"            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"            android:hardwareAccelerated="true"            android:windowSoftInputMode="adjustResize"&gt;            &lt;!-- Specifies an Android theme to apply to this Activity as soon as                 the Android process has started. This theme is visible to the user                 while the Flutter UI initializes. After that, this theme continues                 to determine the Window background behind the Flutter UI. --&gt;            &lt;meta-data              android:name="io.flutter.embedding.android.NormalTheme"              android:resource="@style/NormalTheme"              /&gt;            &lt;!-- Displays an Android View that continues showing the launch screen                 Drawable until Flutter paints its first frame, then this splash                 screen fades out. A splash screen is useful to avoid any visual                 gap between the end of Android's launch screen and the painting of                 Flutter's first frame. --&gt;            &lt;meta-data              android:name="io.flutter.embedding.android.SplashScreenDrawable"              android:resource="@drawable/launch_background"              /&gt;            &lt;intent-filter&gt;                &lt;action android:name="android.intent.action.MAIN"/&gt;                &lt;category android:name="android.intent.category.LAUNCHER"/&gt;            &lt;/intent-filter&gt;        &lt;/activity&gt;        &lt;!-- Don't delete the meta-data below.             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java --&gt;        &lt;meta-data            android:name="flutterEmbedding"            android:value="2" /&gt;    &lt;/application&gt;&lt;/manifest&gt;

these are parameters that I have given in device
wifi_prov_security_t security = WIFI_PROV_SECURITY_0;
 const char *pop = "";
const char *service_key = "abcd@123";        ESP_ERROR_CHECK(wifi_prov_mgr_start_provisioning(security, pop, service_name, service_key)); (edited)

**Comment by omert08** [comment]
AndroidManifest.xml looks okay, 

Please use WIFI_PROV_SECURITY_1 and put a valid pop for both ends. (app and esp32)

I believe there is a fundamental issue in your setup, It doesn't establish the session. if you can explain more about what steps do you follow. I hope I can help.

I hope you don't miss to connect to ESP32's WiFi AP. 

Do you see any error output in ESP32 terminal screen?

**Comment by hipal3101** [comment]
Hi, I am teammate of @devarsh9 .

**Comment by hipal3101** [comment]
output log in ESP32

I (2097) app: SoftAP started
I (2097) app_prov: SoftAP Provisioning started with SSID 'PROV_9764E0', Password 'PROV_PASS'
I (7127) wifi:new:<1,1>, old:<1,1>, ap:<1,1>, sta:<255,255>, prof:1
I (7127) wifi:station: 06:3a:75:f2:5f:a6 join, AID=1, bgn, 40U
I (7157) app: station:06:3a:75:f2:5f:a6 join, AID=1
I (7567) tcpip_adapter: softAP assign IP to station,IP is: 192.168.4.2

After connecting and clicking Ready button in APP there's no output in ESP32
And app keeps scanning

**Comment by omert08** [comment]
Okay, 

You should follow up to find where does it hang. 

`prov = await softApService.startProvisioning("192.168.4.1:80","abcd1234");`

After this line, it goes to the following line,

`var success = await prov.establishSession();`

Put some debug points in establishSession function and check where does it hang? especially if it passes `transport.sendReceive` line or not.

**Comment by hipal3101** [comment]
I think there is problem in wifi scanning so we skipped that part.
So we created a new project in which I called three methods.
1. establishSession
2. sendwificonfig
3. applywificonfig

and it works perfectly in debug mode.
But it doesn't work when we try using after building apk.
