### ISSUE TITLE
Unable to find Security 0 implementation.

### ISSUE THREAD

**Issue by sakina1403** [omert08/esp_softap_provisioning#4]
Hi! I want to communicate using Sec0 and not Sec1, after looking into the package code, I was able to find the classes defined but no implementation methods. Am I missing something or is this yet to be developed?

**Comment by sakina1403** [comment]
I was able to make it work with Security 1, but need to turn off mobile data before sending WiFi Credentials

**Comment by omert08** [comment]
Hi Sakina, 

It has nothing to do with mobile data, you should be connected to your Esp32's AP before start provisioning.

**Comment by sakina1403** [comment]
As it doesn't provide internet, the API call is made via mobile data if it is on. If we turn off mobile data it works fine
