### ISSUE TITLE
Desktop and Web support

### ISSUE THREAD

**Issue by Barabas5532** [omert08/esp_softap_provisioning#5]
What would need to go into adding Desktop and Web support to this? 

It looks like the platform specific code is only for cryptography. Would it be possible to use the [cryptography](https://pub.dev/packages/cryptography) instead, which supports Web and Desktop already?

That package supports both X25519 and AES-CTR (used by esp_prov according to [docs](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/provisioning/provisioning.html#security-schemes). These are implemented in Dart, not native like this package. However, I don't believe there would be any noticeable difference in performance, as we are not sending many messages.

**Comment by Barabas5532** [comment]
I've managed to make it work on Web and Linux Desktop. It probably works on Windows too, but I don't use that for development. I've made a few hacky workarounds, once these are ironed out, I'll send a PR.

https://github.com/Barabas5532/esp_softap_provisioning/tree/feature/web-support

**Comment by omert08** [comment]
Hi @Barabas5532,

Sorry for the late reply. It's been busy weeks. I already use the cryptography library, its version is 2.0.1(not the latest). I've seen your PRs. Let me check.
